services:
  nginx:
    container_name: marks-manager-nginx
    image: nginx:latest
    ports:
      - "18000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/app
    depends_on:
      - web
    restart: unless-stopped

  web:
    container_name: marks-manager-web
    build:
      context: .
      dockerfile: Dockerfile
    image: university-marks-manager:fastapi
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --proxy-headers --workers 2
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db/mydatabase
      - ENABLE_DEBUG_ROUTES=0
      - DEBUG_TOKEN=secret123
    depends_on:
      - db

  db:
    container_name: marks-manager-db
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres_data_nas:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase

volumes:
  postgres_data_nas:
